apiVersion: v1
kind: Secret
metadata:
  name: pipo-secrets
  namespace: pipo-java
type: Opaque
stringData:
  DB_PASSWORD: postgres
  JWT_SECRET: super-secret-key-change-me-to-at-least-32-characters
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipo-config
  namespace: pipo-java
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: pipo_db
  DB_USER: postgres
  SERVER_PORT: "8080"
